import { precacheAndRoute } from 'workbox-precaching';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// 📡 PUSH NOTIFICATION LISTENER
self.addEventListener('push', (event) => {
  if (!event.data) return;

  try {
    const data = event.data.json();
    console.log('[SW] Push Received:', data);

    const options = {
      body: data.body || 'New Tactical assessment detected.',
      icon: '/pwa-192x192.png',
      badge: '/favicon.svg',
      vibrate: [100, 50, 100],
      data: {
        url: data.url || '/'
      },
      actions: [
        {
          action: 'explore',
          title: 'ESTABLISH LINK',
        }
      ]
    };

    event.waitUntil(
      self.registration.showNotification(data.title || 'INCOMING TRANSMISSION', options)
    );
  } catch (err) {
    console.error('[SW] Push processing failed:', err);
  }
});

// Handle notification click
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      const url = event.notification.data.url;
      
      // If a window is already open, focus it and navigate
      for (const client of clientList) {
        if (client.url === url && 'focus' in client) {
          return client.focus();
        }
      }

      // Otherwise, open a new window
      if (clients.openWindow) {
        return clients.openWindow(url);
      }
    })
  );
});
